### ISSUE TITLE
Support enterprise WiFi authentication for use on campus

### ISSUE THREAD

**Issue by tom-parkinson** [IEQLab/samba#12]
It would be good to be able to connect to the University network to support deployments within Wilkinson. ESPHOME supports [enterprise authentication](https://esphome.io/components/wifi.html#enterprise-authentication), but it requires the `esp-idf` framework (we currently use `arduino`). The below code works on a test setup, but we need to determine whether the esp framework will break anything else.

```
wifi:
  networks:
  - ssid: UniSydney
    eap:
      username: "INSERT"
      password: "INSERT"
      ttls_phase_2: mschapv2
  power_save_mode: none
```
